package cs2340.bobzilla.bobs_wallet.model;

import java.io.Serializable;
import java.text.SimpleDateFormat;
import java.util.Date;
import java.util.Locale;

/**
 * Transaction represents a transaction for a User and contains an amount, a
 * type, a date, and a category.
 *
 * @author Farhan
 */
public class Transaction implements Serializable {

    /**
     * Generated by Eclipse.
     */
    private static final long serialVersionUID = 7452030265735708570L;
    /**
     * The amount of the transaction.
     */
    private double amount;
    /**
     * The type of the transaction.
     */
    private TransactionType type;
    /**
     * The date of transaction.
     */
    private String date;
    /**
     * The date format of the transaction.
     */
    public static final String DATE_FORMAT_PATTERN = "MM/dd/yy h:mm a";
    /**
     * The date formatter object for the transaction.
     */
    private SimpleDateFormat sdf = new SimpleDateFormat(DATE_FORMAT_PATTERN,
            Locale.getDefault());
    /**
     * The transaction category.
     */
    private String mCategory;
    
    public static final String PARSE_AMOUNT_KEY = "amount";
    public static final String PARSE_TRANSACTION_TYPE_KEY = "transaction_type";
    public static final String PARSE_DATE_KEY = "date";
    public static final String PARSE_CATEGORY_KEY = "category";
    public static final String PARSE_ASSOCIATED_ACCOUNT_NAME_KEY = "account_name";
    public static final String PARSE_ASSOCIATED_USER_KEY = "user";

    /**
     * Creates a Transaction object given an amount, a type, and a category.
     * 
     * @param inputAmount
     *            The double amount.
     * @param inputType
     *            The TransactionType type.
     * @param inputCategory
     *            The String category.
     */
    public Transaction(double inputAmount, TransactionType inputType, String inputCategory) {
        this.amount = inputAmount;
        this.type = inputType;
        this.date = sdf.format(new Date());
        this.mCategory = inputCategory;
    }

    /**
     * Gets the transaction type.
     * 
     * @return the TransactionType type
     */
    public TransactionType getTransactionType() {
        return type;
    }

    /**
     * Gets the transaction date.
     * 
     * @return the String date
     */
    public String getTransactionDate() {
        return date;
    }

    /**
     * Gets the amount.
     * 
     * @return the double amount
     */
    public double getAmount() {
        return amount;
    }

    /**
     * Gets the category.
     * 
     * @return the String category
     */
    public String getCategory() {
        return mCategory;
    }
}
