package cs2340.bobzilla.bobs_wallet.exceptions;

/**
 * A class to handle invalid registration attempts.
 * 
 * @author jack
 */
public class InvalidRegistrationException extends Exception {
    /**
     * This was generated by eclipse.
     */
    private static final long serialVersionUID = 3727537574941286329L;

    /**
     * Handles invalid registration.
     */
    public InvalidRegistrationException() {
        super();
    }

    /**
     * Handles invalid registration.
     * 
     * @param message
     *            the string message
     */
    public InvalidRegistrationException(String message) {
        super(message);
    }

    /**
     * Handles invalid registration.
     * 
     * @param message
     *            the string message
     * @param cause
     *            the Throwable cause
     */
    public InvalidRegistrationException(String message, Throwable cause) {
        super(message, cause);
    }

    /**
     * Handles invalid registration.
     * 
     * @param cause
     *            the Throwable cause
     */
    public InvalidRegistrationException(Throwable cause) {
        super(cause);
    }

}
