package cs2340.bobzilla.bobs_wallet.exceptions;

public class InvalidLoginException extends Exception {
	/**
	 * This was generated by eclipse.
	 */
	private static final long serialVersionUID = -3467139605660047459L;

	public InvalidLoginException() {
		super();
	}
	
	public InvalidLoginException(String message) {
		super(message);
	}
	
	public InvalidLoginException(String message, Throwable cause) {
		super(message, cause);
	}
	
	public InvalidLoginException(Throwable cause) {
		super(cause);
	}
}
