package cs2340.bobzilla.bobs_wallet.exceptions;

public class InvalidRegistrationException extends Exception {
	/**
	 * This was generated by eclipse.
	 */
	private static final long serialVersionUID = 3727537574941286329L;

	public InvalidRegistrationException() {
		super();
	}
	
	public InvalidRegistrationException(String message) {
		super(message);
	}
	
	public InvalidRegistrationException(String message, Throwable cause) {
		super(message, cause);
	}
	
	public InvalidRegistrationException(Throwable cause) {
		super(cause);
	}
	
}
