package cs2340.bobzilla.bobs_wallet.exceptions;

/**
 * This class is the exception that is thrown by the presenter when the user
 * makes an error while making an account.
 *
 * @author sai
 *
 */
public class InvalidAccountCreationException extends Exception {

    /**
     * This was generated by Eclipse.
     */
    private static final long serialVersionUID = 2179074268783002229L;

    /**
     * This is the constructor for the Invalid Account Creation Exception.
     */
    public InvalidAccountCreationException() {
        super();
    }

    /**
     * This constructor takes in a message that the programmer can access via
     * the getMessage() method.
     *
     * @param detailMessage
     *          The message to be passed along to the user.
     */
    public InvalidAccountCreationException(final String detailMessage) {
        super(detailMessage);
    }

    /**
     * This constructor takes in a throwable so that exceptions can be
     * propagated via. this exception.
     *
     * @param throwable
     *          the throwable to be propagated.
     */
    public InvalidAccountCreationException(final Throwable throwable) {
        super(throwable);
    }

    /**
     * This constructor takes both a throwable and a message so that the user
     * knows what went wrong.
     * @param detailMessage
     *          The message to pass along.
     * @param throwable
     *          The throwable to pass along.
     */
    public InvalidAccountCreationException(final String detailMessage,
            final Throwable throwable) {
        super(detailMessage, throwable);
    }

}
